print('This is Max''s first useable python project, a easy calculator.')
x = int(input('Please enter an number'))
n = input('please enter +, - , *, /')
y = int(input('please enter another number'))
if n =='+': print(x+y)
elif n == '-': print(x-y)
elif n == '*' :print (x*y)
elif n == '/' and y != 0 :print (x/y)
else: print ('this is a serious calculator, dont make jokes of it')
